### PR TITLE
Data raw r

### LINKED ISSUE #36: Update data-raw to R
Right now the initial steps in data-raw are in Python, and are thus opaque to the maintainers. That's a recipe for eventual disaster.

We should rewrite the full process to use R, so we can maintain it.

### PR DESCRIPTION
**Pull request by jonthegeek**
Still in progress (at the time that I created the PR) but I wanted it to live somewhere that you have access.

Closes #36.

### CODE REVIEW

**Comment by jonthegeek** [comment]
I'm running this right now! I *think* I still have at least 1 bug, and eventually we'll probably want to set it up with furrr to speed things up, but the general idea is in place!

**Comment by jonthegeek** [comment]
{goodpractice} says examples are good!

```
> goodpractice::gp(checks = c("rcmdcheck_examples_run_without_warnings"))
Preparing: rcmdcheck

♥ Whoa! Perfect package! Keep up the first-rate work!
```

**Comment by jonthegeek** [comment]
Be sure to squash and merge this one when/if it's ready; no need to keep the aborted attempts at figuring things out in the history 🙃

**Review by Myfanwy — APPROVED** [review]
Apologies for the my delay in reviewing.

**Pull request merged**
