### PR TITLE
update README

### PR DESCRIPTION
**Pull request by maelle**
:wave: @dgrtwo! I added a few badges to the README including the peer-review badge, as well as the markers that'll allow pkgdown to recognize the badges paragraph as such and to transfer badges to the sidebar when building https://docs.ropensci.org/gutenbergr

### CODE REVIEW

**Comment by dgrtwo** [comment]
Thanks!!

**Comment by maelle** [comment]
btw @dgrtwo there is a NOTE in CRAN checks (hence the red CRAN checks badge) -- feel free to drop us a note at rOpenSci if you need any help with this or the package in general (not because of skills, but if you're lacking time for maintenance!).

**Comment by dgrtwo** [comment]
Yep thanks! I've seen the NOTE before and I find I included a release note for CRAN 0.1.3 submission below (though somehow not 0.1.4?)

It comes from the author + titles in the gutenberg_metadata dataset. I don't think there's anything I can do about it (I'm not looking to rename the Brontë siblings 😂)

```
    checking data for non-ASCII 
  characters ... NOTE
      Note: found 13591 marked 
  UTF-8 strings

The marked UTF-8 strings are in the 
  gutenberg_metadata, gutenberg_author
and 
  gutenberg_subject datasets. These accurately 
  represent the titles and
author's names (e.g. 
  "Brontë, Charlotte", or works in 
  Chinese/Japanese)
from Project Gutenberg works, so I 
  have elected not to change them.
```

**Comment by maelle** [comment]
ahahah indeed do not rename them, that is a nice accent :wink:

**Pull request merged**
