### PR TITLE
Use `wget` for downloading

### LINKED ISSUE #85: Usage of `wget` for PG Robot Access Compliance
I noticed that the [PG rules for robot access](https://www.gutenberg.org/policy/robot_access.html) specify use of `wget` and that we reference this in the [README](https://github.com/ropensci/gutenbergr?tab=readme-ov-file#do-you-respect-the-rules-regarding-robot-access-to-project-gutenberg), but currently the package may not actually download using `wget`.

Right now, everything is downloaded in `dl_and_read()` using:
```R
utils::download.file(url, tmp, mode = mode, quiet = TRUE)
```

`utils::download.file` has a `method` param which defaults to `auto`:

```
method: Method to be used for downloading files. Current download methods are ‘"internal"’, ‘"libcurl"’, ‘"wget"’, ‘"curl"’ and ‘"wininet"’ (Windows only), and there is a value ‘"auto"’: see ‘Details’ and ‘Note’.
...
Details:
...
For ‘method = "auto"’ (the default) currently the ‘"internal"’
 method is used for ‘file://’ URLs and ‘"libcurl"’ for all others.
```

Looks like we need to specify `method = "wget"` for compliance, and also verify that `wget` is installed.

### PR DESCRIPTION
**Pull request by jrdnbradford**
Closes #85.

There are many ways this particular issue can be solved, here's one option.

Unfortunately this is currently a breaking change as many users may have been using this without having `wget` installed. Let me know if you think we should perhaps add some logic to allow continued use of non-`wget` methods.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Until we get told to stop, I don't think we should do this. I wouldn't be able to use the package in my normal dev environment for one, and I'm guessing that also goes for the majority of our users. Is there any indication that this rule is anything more than an artifact from old instructions?

**Comment by jrdnbradford** [comment]
@jonthegeek I can see if I can get some clarity via email with them if you like. Then if the decision is to keep as is, we can just update the README.

**Comment by jonthegeek** [comment]
I'm not sure I even read their rules as saying you HAVE to use wget. It's giving it as an example of how to access the files, it seems to me.

**Comment by jrdnbradford** [comment]
Aha, I wonder if my reading is affected by the reference in the README

> Project Gutenberg allows wget to harvest Project Gutenberg using [this list of links](https://www.gutenberg.org/robot/harvest?filetypes%5B%5D=html). The gutenbergr package visits that page once to find the recommended mirror for the user’s location.

and usage of `wget_url` in the code. Might just be artifacts of a time long past.

**Comment by jonthegeek** [comment]
Aha! Yeah, I think we should instead make our reference a bit less specific.

**Comment by jrdnbradford** [comment]
Looking at [Terms of Service](https://www.gutenberg.org/policy/terms_of_use.html) and a mirror's [robots.txt](https://aleph.gutenberg.org/robots.txt), I think you're right. 

I will edit this PR!

**Review by jonthegeek — APPROVED** [review]
This worked out! Thanks for giving me a distraction that I could work through on my phone! (see https://bsky.app/profile/jonthegeek.com/post/3lau5bcqdss2t for why that's helpful today!)

**Pull request merged**
