### PR TITLE
Download `txt` when `zip` not available

### LINKED ISSUE #55: Many common titles cannot be found on any mirror
For some reason, many books that worked fine a few months ago have stopped working with `gutenberg_download()`, regardless of mirror settings.

For example, here are 4 common Shakespearean tragedies:

```r
library(gutenbergr)

tragedy_ids <- c(
  1524,  # Hamlet
  1532,  # King Lear
  1533,  # Macbeth
  1513   # Romeo and Juliet
)

tragedies_raw <- gutenberg_download(
  tragedy_ids,
  meta_fields = "title"
)
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `gutenberg_id = as.integer(gutenberg_id)`.
#> Caused by error:
#> ! `gutenberg_id` must be size 0 or 1, not 4.
#> Run `rlang::last_trace()` to see where the error occurred.
#> Warning messages:
#> 1: ! Could not download a book at http://aleph.gutenberg.org/1/5/2/1524/1524.zip.
#> ℹ The book may have been archived.
#> ℹ Alternatively, You may need to select a different mirror.
#> → See https://www.gutenberg.org/MIRRORS.ALL for options. 
#> 2: ! Could not download a book at http://aleph.gutenberg.org/1/5/3/1532/1532.zip.
#> ℹ The book may have been archived.
#> ℹ Alternatively, You may need to select a different mirror.
#> → See https://www.gutenberg.org/MIRRORS.ALL for options. 
#> 3: ! Could not download a book at http://aleph.gutenberg.org/1/5/3/1533/1533.zip.
#> ℹ The book may have been archived.
#> ℹ Alternatively, You may need to select a different mirror.
#> → See https://www.gutenberg.org/MIRRORS.ALL for options. 
#> 4: ! Could not download a book at http://aleph.gutenberg.org/1/5/1/1513/1513.zip.
#> ℹ The book may have been archived.
#> ℹ Alternatively, You may need to select a different mirror.
#> → See https://www.gutenberg.org/MIRRORS.ALL for options. 
```

That's typically a sign that there are issues with the mirror (see #28), so we can specify a different mirror. Every mirror, however, leads to the same error:

```r
tragedies_raw <- gutenberg_download(
  tragedy_ids,
  meta_fields = "title",
  mirror = "https://mirrors.xmission.com/gutenberg"
)

tragedies_raw <- gutenberg_download(
  tragedy_ids,
  meta_fields = "title",
  mirror = "https://gutenberg.pglaf.org"
)

tragedies_raw <- gutenberg_download(
  tragedy_ids,
  meta_fields = "title",
  mirror = "https://gutenberg.nabasny.com"
)

#> 1: ! Could not download a book at https://mirrors.xmission.com/gutenberg/1/5/2/1524/1524.zip.
#> 1: ! Could not download a book at https://gutenberg.pglaf.org/1/5/2/1524/1524.zip.
#> 1: ! Could not download a book at https://gutenberg.nabasny.com/1/5/2/1524/1524.zip.
```

Visiting the mirror site in a browser and hunting through the file system shows that the corresponding .zip files don't exist there either:

image

That page was last edited on June 27, 2023, so I wonder if something changed on Project Gutenberg's end?

Some of these books have alternative IDs (found with `gutenberg_works()`) that do work, but not all. Romeo and Juliet ([1513](https://gutenberg.org/ebooks/1513)), for instance, does not, which makes it inaccessible

```r
# Hamlet, King Lear, and Macbeth have alternative versions that work:
# 2265 - Hamlet
# 2266 - King Lear
# 2264 - Macbeth

# This works!
some_tragedies <- gutenberg_download(
  c(2265, 2266, 2264),
  meta_fields = "title"
)

# Romeo and Juliet doesn't have an alternative version, so it doesn't work, regardless of the mirror
romeo_juliet <- gutenberg_download(
  1513,
  meta_fields = "title",
  mirror = "https://gutenberg.pglaf.org"
)
#> Warning messages:
#> 1: ! Could not download a book at https://gutenberg.pglaf.org/1/5/1/1513/1513.zip.
#> ℹ The book may have been archived.
#> ℹ Alternatively, You may need to select a different mirror.
#> → See https://www.gutenberg.org/MIRRORS.ALL for options. 
#> 2: Unknown or uninitialised column: `text`. 
```

### PR DESCRIPTION
**Pull request by jrdnbradford**
Closes #55.

This PR looks for the `.zip` options in the mirror, then tries the `.txt` options. I abstracted some `utils` to utilize the same functionality, for example `read_zip_url` becomes `read_url` that reads both file types and loops through using a  new `cycle_through_urls` function.

### CODE REVIEW

**Comment by jrdnbradford** [comment]
I do not have easy access to a Windows machine to troubleshoot why the two tests failed there but not on Mac/Ubuntu. If I had to make a guess based on the logs, I'd say it was something with stripping text.

**Comment by jonthegeek** [comment]
I have access to Windows machines *and* a lot of experience working with text, so I'll take a look!

It will be at least a few days before I'll have a chance to dig into this. I just started a new job, so I'm a bit overloaded with new information by the end of the day 🙃

**Comment by jrdnbradford** [comment]
@jonthegeek I was able to get access for a bit. Both failed tests are apparently due to the behavior of `readr::read_lines` on Windows for reading `.txt` files. It is including `\n` in the strings. I pushed a fix that reads `.txt` files directly from the `url` on Windows instead of from a temp file. It's a bit of a kludge, but the Windows tests are passing now. 🔥 

No rush from me on getting it reviewed, and maybe you can add/update things given your background.

**Comment by jrdnbradford** [comment]
Edited it up a bit after some more investigation:
```R
 mode <- dplyr::if_else(.Platform$OS.type == "windows", "wb", "w")
 utils::download.file(url, tmp, mode = mode, quiet = TRUE)
 readr::read_lines(tmp)
 ```

**Comment by jrdnbradford** [comment]
Did a refactor after looking over the project more. 🚀

**Comment by jrdnbradford** [comment]
@jonthegeek I wanted to follow up on this in case it was forgotten. Hope the new job is going well!

**Comment by jonthegeek** [comment]
@jrdnbradford Not forgotten per se, but I still haven't had a moment to load this back into my mind, unfortunately. Hopefully soon!

**Comment by jonthegeek** [comment]
@jrdnbradford I'm going to try to FINALLY look at this today! I'm so sorry it has taken me so long to get back to this package!

**Review by jonthegeek — APPROVED** [review]
Thank you so much! This looks great!

**Pull request merged**
